[workspace]
resolver = "2"
members = [
  "ohttp-server",
  "cgpuvm-attest",
]

[patch.crates-io]
# The below pacakges requires Rust 1.81 and does not work with Rust 1.75
litemap = { version = "=0.7.4" } 
zerofrom = { version = "=0.1.5" } 