services:
  server:
    image: attested-ohttp-server
    ports:
      - "9443:9443"
    network_mode: "host"
    environment:
      - TARGET=${TARGET}
      - LOCAL_KEY=1
    depends_on:
      - whisper

  whisper:
    image: whisper-api
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    ports:
      - "3000:3000"
