services:
  server:
    image: ohttp-server
    ports:
      - "9443:9443"
    network_mode: "host"
    environment:
      - TARGET=${TARGET}
      - LOCAL_KEY=1
    depends_on:
      - whisper

  whisper:
    image: whisper-api
    network_mode: "host"
    ports:
      - "3000:3000"
